AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AMIId:
    Type: String
    Default: ami-0ff21806645c5e492
  InstanceType:
    Type: String
    Default: t2.micro

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.38.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  ######                                   #     #
  #     # #    # #####  #      #  ####     ##    # ###### ##### #    #  ####  #####  #    #
  #     # #    # #    # #      # #    #    # #   # #        #   #    # #    # #    # #   #
  ######  #    # #####  #      # #         #  #  # #####    #   #    # #    # #    # ####
  #       #    # #    # #      # #         #   # # #        #   # ## # #    # #####  #  #
  #       #    # #    # #      # #    #    #    ## #        #   ##  ## #    # #   #  #   #
  #        ####  #####  ###### #  ####     #     # ######   #   #    #  ####  #    # #    #
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.38.0.0/24
      AvailabilityZone: !Select
      - 0
      - Fn::GetAZs: !Ref AWS::Region
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
  PublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref Vpc
  PublicRoute1:
    Type: AWS::EC2::Route
    Properties:
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PublicRouteTable

  ######                                         #     #
  #     # #####  # #    #   ##   ##### ######    ##    # ###### ##### #    #  ####  #####  #    #
  #     # #    # # #    #  #  #    #   #         # #   # #        #   #    # #    # #    # #   #
  ######  #    # # #    # #    #   #   #####     #  #  # #####    #   #    # #    # #    # ####
  #       #####  # #    # ######   #   #         #   # # #        #   # ## # #    # #####  #  #
  #       #   #  #  #  #  #    #   #   #         #    ## #        #   ##  ## #    # #   #  #   #
  #       #    # #   ##   #    #   #   ######    #     # ######   #   #    #  ####  #    # #    #
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: 10.38.1.0/24
      AvailabilityZone: !Select
      - 1
      - Fn::GetAZs: !Ref AWS::Region
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
  PrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet

  PublicInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet:
        - !GetAtt Vpc.DefaultSecurityGroup
        SubnetId: !Ref PublicSubnet
      Tags:
      - Key: Name
        Value: PublicInstance

  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet:
        - !GetAtt Vpc.DefaultSecurityGroup
        SubnetId: !Ref PrivateSubnet
      Tags:
      - Key: Name
        Value: PrivateInstance

  InstanceServerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
       Version: 2012-10-17
       Statement:
       - Effect: Allow
         Principal:
           Service:
           - ec2.amazonaws.com
         Action:
            - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref InstanceServerRole

Outputs:
  ManagedInstancesUrl:
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/systems-manager/managed-instances?region=${AWS::Region}"
